### ISSUE TITLE
Latest forego version immediately crashes for rails / node app

### ISSUE THREAD

**Issue by ecbrodie** [ddollar/forego#101]
I have been using the version of Forego from Homebrew (released in April 2016) for months on my rails server, node client application without significant issue. The Procfile that I run using `forego start` contains the following:

```
server: rails s
client: yarn run start;
```

I noticed that there is a later version of Forego released on Equinox and the Homebrew version of it is no longer being updated, as noted in https://github.com/ddollar/forego/issues/74. So I removed the Homebrew version of Forego and tried to install the newer version, both through the executable in Equinox and also the command from the README to build from source. In both instances, `forego start` is immediately failing with no indication about why. This is the output:

```
forego      | starting server.1 on port 5000
forego      | starting client.1 on port 5100
forego      | starting envlog.1 on port 5300
forego      | starting stdoutlog.1 on port 5600
forego      | starting stderrlog.1 on port 6000
forego      | sending SIGTERM to server.1
forego      | sending SIGTERM to stderrlog.1
forego      | sending SIGTERM to stdoutlog.1
forego      | sending SIGTERM to envlog.1
forego      | Grace time expired
forego      | Killing stdoutlog.1
```

I have confirmed that it is neither caused by an error in the `rails s` nor the `yarn run start` commands, as I can run my app just fine when I manually run these commands. If there is a log file that Forego outputs, then I could `tail -f` the logs and try to investigate more, but unfortunately I am not sure if I have that to my disposal.

Any idea what might be the problem and how I can further troubleshoot this problem?

**Side question:** What is the motivation to no longer maintaining the Homebrew package for Forego? I understand why Equinox is important for Go applications, but Homebrew has become the universally accepted package manager for CLI tools on Mac.

**Comment by ddollar** [comment]
I'm not really maintaining anything for forego any more. Equinox made for less work and AFAIK they offer a homebrew tap built in.

Thank you for submitting this issue but I am going to go ahead and close it as I haven't been able to reproduce. If you hunt it down would gladly accept a PR to fix!

**Comment by ecbrodie** [comment]
Hi @ddollar , thank you for your reply. I am saddened to hear about Forego's status, but I understand. I will submit a PR if I get around to solving the issue.

Can you confirm, though, that Foreman is still being maintained? Thank you.

**Comment by ddollar** [comment]
Yes, though Foreman is in a feature freeze.
