### ISSUE TITLE
PORT env var dependent on the position in the Procfile

### ISSUE THREAD

**Issue by fidalgo** [ddollar/forego#103]
Hi!

I've found a weird behaviour, that I was able to track after some hit and miss!

Having a trivial `Procfile`:
```
web: bundle exec puma -C config/puma.rb
consumer: bundle exec ruby bin/consumer.rb
```

And having set some environment variables through docker-compose files, namely the `PORT`, I've noticed that forego (and foreman) sets a different port for each service.
Since only the `web` service has a port assigned, if I do not set it the first line of the `Procfile` it will use a different port than the one I expect.

Here are the outputs:

```
./forego start
forego  | starting consumer.1 on port 4567
forego  | starting web.1 on port 4667
```
Switching...
```
./forego start
forego  | starting web.1 on port 4567
forego  | starting consumer.1 on port 4667
```
As a side note, if I have code to print the environment variables, I see the value of 'PORT' changed.

**Comment by liamdawson** [comment]
Just checking @fidalgo -- you may have already discovered this, but `$PORT` has special behaviour under Foreman: https://ddollar.github.io/foreman/#PROCFILE

**Comment by fidalgo** [comment]
thanks @liamdawson for the heads up! I've ended up to figure out, will close as it's not an issue.
