### ISSUE TITLE
equinox.io shutting down, publish builds elsewhere?

### ISSUE THREAD

**Issue by bjozet** [ddollar/forego#126]
Noticed that equinox.io is shutting down and removing all apps and accounts by 30th sept 2021. (https://equinox.io/blog/shutting-down)

Thought i'd report it, in case you didn't know.
Thanks for your efforts in this project! :)

**Comment by niko** [comment]
Any news here?

**Comment by bjozet** [comment]
resorting to building it myself :)

**Comment by viranch** [comment]
Consider uploading to GitHub releases?
