### ISSUE TITLE
Default port behavior differs from Foreman

### ISSUE THREAD

**Issue by joeyespo** [ddollar/forego#44]
I was trying to use alternatives to Foreman, since it was a little buggy with file handling, and I noticed some differences. 

I set up [this gist](https://gist.github.com/joeyespo/9e8a47f526c27e6abbab) after writing one [for Honch](https://gist.github.com/joeyespo/3c210b2b6504531bc230) to test and demonstrate the differences:

- Foreman's port precedence is `-p option`, `.env file`, `PORT variable`, `default of 5000`
- Forego's port precedence is `PORT variable`, `-p option`, `default of 5000`

Forego completely ignores the `PORT` variable in `.env`, which could actually be classified as a completely different issue.

**Comment by ddollar** [comment]
Looks like you're right. Would you be interested in trying to put together a pull request to correct this?

**Comment by ddollar** [comment]
Actually looks like this is covered by #45

**Comment by joeyespo** [comment]
Nice!

**Comment by joeyespo** [comment]
Ok, just tested it with the latest build.

#45 did fix the .env problem, but the order is still wrong:

- Foreman's port precedence is `-p option`, `.env file`, `PORT variable`, `default of 5000`
- Forego's port precedence is `PORT variable`, `-p option`, `.env file`, `default of 5000`

Put another way, if `PORT` just so happens to be in your ENV for another reason, you can't override it using `.env` or even `-p`.

**Comment by nhocki** [comment]
@joeyespo I just tested this and the order seems to be:

1. `-p` flag
2. `PORT` variable in the `.env` file
3. Default `5000` port.

Here's what I have:

.env

```
PORT=6000
```

Procfile
```
test: ruby test.rb
```

test.rb

```ruby
puts ENV['PORT'].inspect
```

----

Running:

1: `forego start -p 4000`

```
forego | starting test.1 on port 4000
test.1 | "4000"
```

2. `forego start`

```
forego | starting test.1 on port 6000
test.1 | "6000"
```

3. (After removing the `.env` file) `forego start`

```
forego | starting test.1 on port 5000
test.1 | "5000"
```

---

The thing that seems to be missing in #45 is to read directly from the environment.

**Comment by ddollar** [comment]
The precedence that makes the most sense to me is:

* `-p` option
* `PORT` environment variable
* `PORT` in `.env`
* 5000

I'd accept pull requests to both foreman and forego to match up with this if anyone is feeling up to it.

**Comment by nhocki** [comment]
I can add that, after @sergiobuj PR, only the `PORT` environment variable is missing.
