### ISSUE TITLE
ARM builds

### ISSUE THREAD

**Issue by moul** [ddollar/forego#47]
Hi,
Can you add ARM builds ?

linux-armel: GOOS=linux GOARCH=arm GOARM=5
linux-armhf: GOOS=linux GOARCH=arm GOARM=6

Thank you

**Comment by ddollar** [comment]
You can find some ARM builds here:

http://gobuild.io/github.com/ddollar/forego

**Comment by moul** [comment]
Thank you !

**Comment by djmaze** [comment]
gobuild.io seems to be down?
