### ISSUE TITLE
Env file not loaded when specified full-path

### ISSUE THREAD

**Issue by bartmeuris** [ddollar/forego#49]
On Linux, using version 0.15.0, when you specify the full-path to the environment file to load, it fails. When specifying a relative path, it works:

ProcFile.test:
```
test: echo "-- $FOO --"
```

testenv:
```
FOO=123
EXE=echo
```

Starting with these files normally just works:

```
$  forego start -f ProcFile.test -e testenv
forego | starting test.1 on port 5000
test.1 | -- 123 --
$
```

When Specifying full-path for the env file, the environment variables are not loaded:
```
$  forego start -f ProcFile.test -e ${PWD}/testenv
forego | starting test.1 on port 5000
test.1 | --  --
$
```

This used to work correctly in 0.13.1

**Comment by ddollar** [comment]
Does ${PWD} contain a space?

**Comment by bartmeuris** [comment]
No it does not - the example above was in tested in `/home/vagrant`

**Comment by tehbilly** [comment]
Question, what platform are you trying this on? I wasn't able to duplicate this on my Arch box or my Windows machine.

That's not entirely true, I was able to replicate it on Windows inside of cygwin, but nowhere else.

**Comment by bartmeuris** [comment]
I tested this in Ubuntu 14.04 in Vagrant (and in an Ubuntu 14.04 Docker container where I first encountered the problem, and was able to replicate it in a VM). Note that I also tried typing out the complete path (so it's not the ${PWD} substitution)

**Comment by jmervine** [comment]
Mind including the output for the following commands:

1. `echo $PWD`
2. `pwd`
3. `echo "forego start -f ProcFile.test -e ${PWD}/testenv"` << redundant, but still

Also try: `forego start -f ProcFile.test -e /home/vagrant/testenv` (per your comments above).

**Comment by paulmelnikow** [comment]
I can reproduce this on Mac OS X Yosemite 10.10.5.

Works (i.e. spits out the ADMIN keys I expect):

```
forego run -e .env env | grep ADMIN
forego run -e ./.env env | grep ADMIN
```

Doesn't work:
```
forego run -e ~/.code/core/.env env | grep ADMIN
forego run -e /Users/pnm/code/core/.env env | grep ADMIN
```

```
$ echo "$PWD"
/Users/pnm/code/core
$ pwd
/Users/pnm/code/core
$ forego run -e ${PWD}/.env env | grep ADMIN
$ forego run -e /Users/pnm/code/core/.env env | grep ADMIN
```

**Comment by paulmelnikow** [comment]
Ah, this works for me in 4eaf54121ea534d09e704a1227da35198e1ce283, can you push a release?
