### ISSUE TITLE
Only first line of output is printed

### ISSUE THREAD

**Issue by kjk** [ddollar/forego#51]
This might be by design, but when app logs multiple lines, forego only prints the first one, probably because of buffer.Reset() in LineReader http://gotools.org/github.com/ddollar/forego#OutletFactory.LineReader

This is problematic e.g. for panics, because important information is not shown.

**Comment by ngrilly** [comment]
Same problem here. I remember that the first versions of forego didn't have this issue.

**Comment by aripollak** [comment]
I think I'm running into this. Would you mind releasing a new version of the package?
