### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by techtonik** [ddollar/forego#54]
http://blog.daviddollar.org/2011/05/06/introducing-foreman.html

This one is awesome. I wonder if there is a chapter 2 of evolution of foreman/forego.

**Comment by vlcinsky** [comment]
In fact, existing doc of this excellent tool is a bit too short. It took me a while to find out that I shall consult Foreman documentation (simple link would help as there is another project called Foreman, even thought that one did not learn about beauty of simplicity as much as this one).

The other problem is, that not all the features from foreman are implemented in forego (or at least it did not work for me) and it takes a moment to do own experimental research, what it really provides.

**Comment by ddollar** [comment]
A user contributed some more docs but given this project's status (a toy project I used to learn go and haven't touched much since) I don't think it will receive much more maintenance.

I'd happy review any PRs if you feel up to it, though!
