### ISSUE TITLE
python output not displaying

### ISSUE THREAD

**Issue by dickeyxxx** [ddollar/forego#62]
I think there is maybe a stdout flushing issue when using forego on windows. It doesn't display output from this django app: https://github.com/heroku/python-getting-started

```
C:\Users\IEUser\tmp\python-getting-started>type Procfile
web: python manage.py runserver 0.0.0.0:5000
 
C:\Users\IEUser\tmp\python-getting-started>forego start web
forego | starting web.1 on port 5000
 
C:\Users\IEUser\tmp\python-getting-started>python manage.py runserver 0.0.0.0:5000
July 08, 2015 - 15:01:47
Django version 1.8.1, using settings 'gettingstarted.settings'
Starting development server at http://0.0.0.0:5000/
Quit the server with CTRL-BREAK.
[08/Jul/2015 15:01:51]"GET / HTTP/1.1" 200 6525
[08/Jul/2015 15:01:51]"GET /static/lang-logo.png HTTP/1.1" 304 0
```

It still functions, but it doesn't display any output. After I press ctrl-c, it does show one line of output.

**Comment by dickeyxxx** [comment]
cc @kennethreitz

**Comment by kron4eg** [comment]
@dickeyxxx is it showing output under regular foreman?

**Comment by dickeyxxx** [comment]
yes it does

**Comment by jamesbeith** [comment]
I'm getting this same issue on OS X.

**Comment by bgentry** [comment]
@ddollar I feel like this is probably identical to an issue you fixed w/ Convox a while ago that's caused by python never outputting newlines

**Comment by ddollar** [comment]
Seems very likely I just don't have the bandwidth to fix it right now :)

**Comment by dickeyxxx** [comment]
mind elaborating more on what the issue was? I could take a pass at fixing it. btw expect more bug reports and forego usage, we switched to forego in all the Heroku documentation (via the `heroku local` command)

**Comment by ddollar** [comment]
In outlet.go it waits for a new line to display anything. Happy to give you a commit but if you like.

**Comment by kennethreitz** [comment]
It's not that python doesn't "output" newlines, it's that Python doesn't flush stdout when it prints a newline. Most languages do.

**Comment by brandonb927** [comment]
We stopped using forego after about an hour because of this issue :( Anything we can add to our django stack to allow us to use forego?

**Comment by dickeyxxx** [comment]
I'm trying to figure out how to get the subprocess to flush in order to fix this, but you might be able to fix this in your procfile by adding `2>&1` to the end of the command

**Comment by ddollar** [comment]
Set PYTHONUNBUFFERED to a non-empty string

https://docs.python.org/2/using/cmdline.html#envvar-PYTHONUNBUFFERED

**Comment by dickeyxxx** [comment]
`PYTHONUNBUFFERED` doesn't seem to work:
```
env PYTHONUNBUFFERED=0 forego start -f fixtures/python/Procfile
forego | starting out.1 on port 5000
out.1  | foo
```

here's the fixture I'm using: https://github.com/ddollar/forego/compare/master...dickeyxxx:python-sync?expand=1

that branch also fixes the problem, but I'm not sure it's the best solution

**Comment by kennethreitz** [comment]
`PYTHONUNBUFFERED` is for controlling python's pipe buffering, and while it can be useful on the consumption end of this problem (e.g. writing forego in python), it should have no effect on this.

The problem is that go is only printing lines when they are flushed, and python simply does not flush lines usually.

**Comment by aristidesfl** [comment]
I'm also having problems getting proper stack traces from flask

**Comment by aristidesfl** [comment]
My procfile:
```
dev: python main.py
web: gunicorn main:app --log-file=-
```

With `forego start dev`, I don't get proper stack traces.
With `forego run python main.py` I get full stack trace.

Ruby foreman works fine in both cases.
Aren't both commands supposed to have exactly the same result?

**Comment by ddollar** [comment]
For now forego is going to assume that subprocesses flush their output regularly. If any Pythonistas want to take a swing at fixing this globally please feel free to submit a PR!
