### ISSUE TITLE
error output not complete

### ISSUE THREAD

**Issue by ianstormtaylor** [ddollar/forego#67]
Running into an issue where `forego` doesn't seem to be giving all of the error output that regular `foreman` used to (and still does). In a node setup with a `server.js` that just errors out...

```javascript
throw new Error('stop!');
```

With `foreman`, I get a full stack trace:

```
$ foreman start
17:29:48 web.1  | started with pid 2303
17:29:48 web.1  | /Users/Storm/dev/ianstormtaylor/damp-retreat-7073/server.js:2
17:29:48 web.1  | throw new Error('stop!');
17:29:48 web.1  | ^
17:29:48 web.1  | Error: stop!
17:29:48 web.1  |     at Object.<anonymous> (/Users/Storm/dev/ianstormtaylor/damp-retreat-7073/server.js:2:7)
17:29:48 web.1  |     at Module._compile (module.js:434:26)
17:29:48 web.1  |     at Object.Module._extensions..js (module.js:452:10)
17:29:48 web.1  |     at Module.load (module.js:355:32)
17:29:48 web.1  |     at Function.Module._load (module.js:310:12)
17:29:48 web.1  |     at Function.Module.runMain (module.js:475:10)
17:29:48 web.1  |     at startup (node.js:117:18)
17:29:48 web.1  |     at node.js:951:3
17:29:48 web.1  | exited with code 1
17:29:48 system | sending SIGTERM to all processes
SIGTERM received
```

But with `forego` I only get the offending line, which makes it super hard to debug issues:

```
$ forego start
forego | starting web.1 on port 5000
web.1  | /Users/Storm/dev/ianstormtaylor/damp-retreat-7073/server.js:2
```
```
$ heroku local
forego | starting web.1 on port 5000
web.1  | /Users/Storm/dev/ianstormtaylor/damp-retreat-7073/server.js:2
```

Am I doing something wrong? Would love to get this fixed, since it makes it impossible to quickly resolve errors when using `heroku local`. Thanks!

**Comment by dickeyxxx** [comment]
it might be this issue https://github.com/ddollar/forego/issues/62

does it work if you append `2>&1` to the end of the command in the profile?

**Comment by ianstormtaylor** [comment]
Hmm, nope, appending `2>&1` doesn't seem to do anything. (Except losing coloration of text.)

**Comment by dickeyxxx** [comment]
this was fixed in this pr actually https://github.com/ddollar/forego/pull/52
@ddollar can you push a new release?

**Comment by bostwick** [comment]
I'm running into this as well. I'm running both `heroku local` and forego installed via homebrew on OS X.

```
$ forego start
forego | starting web.1 on port 5000
web.1  | 2015-09-17T19:01:38.343Z - info: Loading config for environment staging from ./config/staging
web.1  | /Users/daniel/Development/bostwick-climb-higher-api/src/climb-higher/database.js:9
web.1  | er:3:19)
```

```
$ forego version
0.16.1
```

**Comment by dickeyxxx** [comment]
as I said, this is fixed, we just need to push a release

**Comment by AnilRedshift** [comment]
+1 for pushing a new release. Thanks!

**Comment by schreifels** [comment]
@dickeyxxx @ddollar Would love to see a release that contains this fix, thanks!

**Comment by raimo** [comment]
+1 on getting this out.

**Comment by mikaa123** [comment]
Hi there :)
Would love to have this out too!

**Comment by HPF-MCompeau** [comment]
Would love to see this fix get out!

**Comment by aaronshaf** [comment]
@ddollar Can you please push a release?

**Comment by ddollar** [comment]
Finally fixed up the release process using Equinox. Check the README for download links.
