### ISSUE TITLE
Links to the precompiled binaries seem to be broken

### ISSUE THREAD

**Issue by barsteadr** [ddollar/forego#81]
Clicking on any of the binary download links shown on the README (or attempting a `wget`) fails.

Example:

[Linux](https://godist.herokuapp.com/projects/ddollar/forego/releases/current/linux-amd64/forego)

leads to an error page that shows this:

```
An error occurred in the application and your page could not be served. 
Please try again in a few moments.
If you are the application owner, check your logs for details.
```

Links have been broken since 3 PM CST on March 27th.

**Comment by Ewarren7** [comment]
Looks like this is also breaking [Heroku Local CLI plugin](https://devcenter.heroku.com/articles/heroku-local), which uses forego.

**Comment by dickeyxxx** [comment]
@Ewarren7 heroku local no longer uses forego

**Comment by dmp1ce** [comment]
I'm noticing this as well. I use Forego in some Dockerfiles.

**Comment by browny** [comment]
same here, is there any other links to download it?

**Comment by EHER** [comment]
same problem here.

**Comment by RyanBalfanz** [comment]
same

**Comment by dfguo** [comment]
seeing it broken too

**Comment by ddollar** [comment]
Using Equnox now, should be fixed.
