### ISSUE TITLE
Proc names with dashes not working in 0.16.1 but works in master

### ISSUE THREAD

**Issue by zph** [ddollar/forego#87]
First off, thanks for having a golang tool vs requiring ruby toolchain 👍 .

I found this bug while trying out the following project https://github.com/shakacode/react-webpack-rails-tutorial/, specifically the Procfiles there. 

Sample Procfile.dev from tutorial:

```
# Basic procfile for dev work.
# Runs all processes. Development is faster if you pick one of the other Procfiles if you don't need
# some of the processes: Procfile.hot or Procfile.express

# Development rails requires both rails and rails-assets
# (and rails-server-assets if server rendering)
rails: REACT_ON_RAILS_ENV=HOT rails s -b 0.0.0.0

# Run the hot reload server for client development
hot-assets: sh -c 'rm app/assets/webpack/* || true && HOT_RAILS_PORT=3500 npm run hot-assets'

# Render static client assets
rails-static-client-assets: sh -c 'npm run build:dev:client'

# Render static client assets. Remove if not server rendering
rails-static-server-assets: sh -c 'npm run build:dev:server'

# Run an express server if you want to mock out your endpoints. No Rails involved!
# Disable this if you are not using it.
# It's a great way to prototype UI especially with non-Rails developers!
express: sh -c 'HOT_PORT=4000 npm start'
```

That procfile works under foreman but not under forego 0.16.1.

If I change the `rails: ` line slightly (use `sh -c` around command) it will also work under master copy of forego.

If I make the following changes (in PR https://github.com/shakacode/react-webpack-rails-tutorial/pull/310/files) then it works under forego... ie changing the names from dash delimited to underscore delimited (`s/hot-assets/hot_assets/g`), then it works under forego 0.16.1.

So seems like something changed for the better between 0.16.1 and now. My thought is that dashes are considered permissible according to forego's regex (https://github.com/ddollar/forego/blob/master/procfile.go#L12) and should work.

Does it make sense to cut another release for forego since it's working better in master?

**Comment by zph** [comment]
Ah, in v0.16.1, this was the regex:

https://github.com/ddollar/forego/blob/db3ef40c253be503beeee0703b71fb331eb2e794/procfile.go#L13

vs now... when there's a `-`

https://github.com/ddollar/forego/blob/9bebfece50af7d2c2d6e7bfc727fe27f7b3f0a12/procfile.go#L12

Which was changed in this commit:

`62551d4c (Satoshi Ebisawa 2016-04-14 05:07:35 +0900)`

Guess my issue is a request for cutting a new release and no code changes are needed.

**Comment by ddollar** [comment]
New release has been cut, thanks for the report :)

**Comment by tomwhoiscontrary** [comment]
Is this release available anywhere?
