### ISSUE TITLE
Immediate exit when using reflex OSX

### ISSUE THREAD

**Issue by hkparker** [ddollar/forego#94]
forego is incompatible with github.com/cespare/reflex on OSX.  Its pretty bizarre.

Trivial example works fine:

```
$ cat Procfile
service: nc -l 5000
$ forego start
forego              | starting service.1 on port 5000
```

Multiple netcat services are fine as well.  But add a trivial reflex example:

```
$ cat Procfile
service: nc -l 5000
api: reflex -r '\.go$' -s -- sh -c 'ls'
$ forego start
forego              | starting service.1 on port 5000
forego              | starting api.1 on port 5100
api.1               | [00] Starting service
forego              | sending SIGTERM to service.1
$
```

And everything is terminated immediately.  If I run reflex by itself however all is well:

```
$ reflex -r '\.go$' -s -- sh -c 'ls'
[00] starting service
<ls output and waits for changes>
```

And this only happens on OSX, linux is alright.

**Comment by chenyingyin** [comment]
![default](https://cloud.githubusercontent.com/assets/24284270/20781549/9c7adc26-b7be-11e6-8b2e-db7b976e3f49.png)

**Comment by ddollar** [comment]
Not sure what's happening here but since I'm not actively maintaining this project I'm going to close this issue. Please feel free to open a PR if you track it down.

**Comment by hkparker** [comment]
Wait, what?  You are closing an issue because you aren't maintaining a project?  I would expect even if you don't plan on actively working on issues you would leave them up for others to see.  That's valuable because then one can check if others have experienced the same problem, and gives them a place to discuss fixes, even without your involvement.  It seems like you just don't want any open issues, even if there are valid bugs.

**Comment by dradtke** [comment]
I've been running into this as well. Strangely, this fails:

```
web: reflex --conf web/reflex.conf
```

but this seems to work:

```
web: bash -c 'true && reflex --conf web/reflex.conf'
```

Just _why_ this works is beyond me, but it could be a workaround.
